server:
  port: 8081

spring:
  application:
    name: ms-usuarios

  # 🔌 Configuración del origen de datos (Mapeado dinámico para Docker o Local)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_usuarios}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # 🗄️ Configuración de JPA e Hibernate (Con formateo de SQL activado)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true # Ejecuta la inicialización SQL después de Hibernate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # ⚙️ Inicializador SQL (Migrado de tu properties)
  sql:
    init:
      mode: always
      separator: "//"

  # 🐇 Configuración del Broker de Mensajería RabbitMQ
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

# 🌐 Registro e integración en el Servidor Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true


